version: '3.8'

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.0#configuration for more options
      PBF_URL: https://download.geofabrik.de/asia/azerbaijan-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/asia/azerbaijan-updates/
      NOMINATIM_PASSWORD: nominatim
      NOMINATIM_TOKENIZER: icu
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

volumes:
  nominatim-data: